### PR TITLE
Added Ludicrous Propulsion Systems to Engine Igniter

### PR DESCRIPTION
**Pull request by AmberCronin**

### CODE REVIEW

**Comment by jamesharling** [comment]
Thanks for the PR. Could you do the following before a merge?

- [x] Add `.cfg` extension to Engines patch
- [x] Update MM targets and module names in Engines patch, the target/module is `EngineIgniter`, not `EngineIgnitor`
- [x] Duplicate Engines patch in `/GameData/EngineIgniter/` (this folder is the redist)

**Comment by AmberCronin** [comment]
Ok, all done!

**Comment by jamesharling** [comment]
Thanks for the updates. If you can lastly just add a file extension to: `/src/EngineIgniter/PartPatches/Engines-LudicrousPropulsionSystems` then I'll get this merged! The rest all looks good to me.

**Comment by jamesharling** [comment]
I'll get a new release built ASAP.

**Comment by AmberCronin** [comment]
Cool. Good working with you, sir!

**Comment by jamesharling** [comment]
@BenjaminCronin is your mod on CKAN? If so, what's the identifier for your mod?

**Comment by AmberCronin** [comment]
Just LudicrousPropulsionSystems. Why?

**Comment by jamesharling** [comment]
I'll add it to the suggested mods when EngineIgniter is installed via CKAN.

**Pull request merged**
